export type Platform = 'Twitch' | 'YouTube';
export type KickStatus = 'Active on Kick' | 'No Kick presence' | 'Unverified';

export interface Creator {
  id: string;
  channelName: string;
  firstName: string;
  platform: Platform;
  profileUrl: string;
  /** Average concurrent viewers over the snapshot window. */
  acv: number;
  /** Hours streamed in the snapshot window. */
  hoursStreamed: number;
  followers: number;
  /** ISO date. Compared against SNAPSHOT_DATE, never against "today". */
  lastLive: string;
  kickStatus: KickStatus;
  /** Unstructured about-page / link-in-bio scrape. What enrichment reads. */
  aboutText: string;
  /** Ground-truth business address on file from discovery. null = none published. */
  seededEmail: string | null;
}

/**
 * The roster is a frozen snapshot, so "days since last live" is measured from
 * this date rather than from the clock. A demo whose filters drift as the
 * calendar moves is not reviewable.
 */
export const SNAPSHOT_DATE = '2026-08-17';

export const creators: Creator[] = [
  {
    id: 'c001',
    channelName: 'AshVelocity',
    firstName: 'Ashley',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/ashvelocity',
    acv: 1840,
    hoursStreamed: 214,
    followers: 412000,
    lastLive: '2026-08-16',
    kickStatus: 'No Kick presence',
    aboutText:
      '[BIO] FPS ranked grind + Friday subathons. she/her. [LINKS] linktr.ee/ashvelocity | discord.gg/ashvel [BUSINESS] all sponsorships + product seeding ➜ ash (at) ashvelocity (dot) tv — please no DMs, they get buried',
    seededEmail: 'ash@ashvelocity.tv',
  },
  {
    id: 'c002',
    channelName: 'NovaGrindTV',
    firstName: 'Marcus',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/novagridtv',
    acv: 920,
    hoursStreamed: 168,
    followers: 188000,
    lastLive: '2026-08-15',
    kickStatus: 'Active on Kick',
    aboutText:
      '[BIO] Simulcasting since March. [BUSINESS] marcus@novagrind.tv [LINKS] kick.com/novagrind',
    seededEmail: 'marcus@novagrind.tv',
  },
  {
    id: 'c003',
    channelName: 'PixelHermit',
    firstName: 'Dana',
    platform: 'YouTube',
    profileUrl: 'https://youtube.com/@pixelhermit',
    acv: 640,
    hoursStreamed: 142,
    followers: 305000,
    lastLive: '2026-08-14',
    kickStatus: 'No Kick presence',
    aboutText:
      '[ABOUT] Cozy builder VODs, 4 uploads a week, no face cam. [BIO] dm me memes not decks [BOOKING] brand work: booking [at] pixelhermit [dot] gg',
    seededEmail: 'booking@pixelhermit.gg',
  },
  {
    id: 'c004',
    channelName: 'RiftWardenLive',
    firstName: 'Tomas',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/riftwardenlive',
    acv: 1470,
    hoursStreamed: 251,
    followers: 233000,
    lastLive: '2026-08-16',
    kickStatus: 'No Kick presence',
    aboutText:
      '[BIO] MOBA coach, 9 years on platform. [MANAGEMENT] repped for all commercial deals — hello@loadedgg.agency [LINKS] twitter.com/riftwarden',
    seededEmail: 'hello@loadedgg.agency',
  },
  {
    id: 'c005',
    channelName: 'SableRoute',
    firstName: 'Priya',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/sableroute',
    acv: 505,
    hoursStreamed: 96,
    followers: 74000,
    lastLive: '2026-08-13',
    kickStatus: 'Unverified',
    aboutText:
      '[BIO] speedruns + travel IRL. fan mail and clips: sableroute.fan@gmail.com [BOOKING] partnerships only ➜ priya@sableroute.co [LINKS] instagram.com/sableroute',
    seededEmail: 'priya@sableroute.co',
  },
  {
    id: 'c006',
    channelName: 'KettleAndCrown',
    firstName: 'Ben',
    platform: 'YouTube',
    profileUrl: 'https://youtube.com/@kettleandcrown',
    acv: 380,
    hoursStreamed: 121,
    followers: 156000,
    lastLive: '2026-08-12',
    kickStatus: 'No Kick presence',
    aboutText:
      '[ABOUT] Tea, tabletop, and long-form lore videos. [CONTACT] ben@kettleandcrown.com',
    seededEmail: 'ben@kettleandcrown.com',
  },
  {
    id: 'c007',
    channelName: 'VoidPacer',
    firstName: 'Ines',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/voidpacer',
    acv: 2310,
    hoursStreamed: 288,
    followers: 640000,
    lastLive: '2026-08-15',
    kickStatus: 'Active on Kick',
    aboutText:
      '[BIO] top-100 variety. [BUSINESS] ines AT voidpacer DOT gg [LINKS] kick.com/voidpacer (exclusive from Jan)',
    seededEmail: 'ines@voidpacer.gg',
  },
  {
    id: 'c008',
    channelName: 'HollowBeamGG',
    firstName: 'Kai',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/hollowbeamgg',
    acv: 760,
    hoursStreamed: 187,
    followers: 129000,
    lastLive: '2026-08-11',
    kickStatus: 'No Kick presence',
    aboutText:
      '[BIO] horror games, 3am starts, no schedule. [LINKS] discord.gg/hollowbeam — business enquiries go through the Discord mod ticket system only, we do not publish an address',
    seededEmail: null,
  },
  {
    id: 'c009',
    channelName: 'MarrowMapper',
    firstName: 'Sofia',
    platform: 'YouTube',
    profileUrl: 'https://youtube.com/@marrowmapper',
    acv: 410,
    hoursStreamed: 74,
    followers: 98000,
    lastLive: '2026-08-14',
    kickStatus: 'No Kick presence',
    aboutText:
      '[ABOUT] Soulslike deep dives and boss maths. [FOOTER] press + sponsor: sofia@marrowmapper.tv | agency-free, I answer myself',
    seededEmail: 'sofia@marrowmapper.tv',
  },
  {
    id: 'c010',
    channelName: 'GreyLadderTV',
    firstName: 'Owen',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/greyladdertv',
    acv: 1180,
    hoursStreamed: 232,
    followers: 271000,
    lastLive: '2026-08-16',
    kickStatus: 'No Kick presence',
    aboutText:
      '[BIO] racing sim league host. [MANAGEMENT] owen@apexcreators.co handles the calendar [LINKS] youtube.com/@greyladder',
    seededEmail: 'owen@apexcreators.co',
  },
  {
    id: 'c011',
    channelName: 'QuartzHalo',
    firstName: 'Lena',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/quartzhalo',
    acv: 340,
    hoursStreamed: 88,
    followers: 61000,
    lastLive: '2026-08-13',
    kickStatus: 'Unverified',
    aboutText:
      '[BIO] chill farming sims + chat karaoke [PINNED] for collabs email lena [at] quartzhalo [dot] live (checked weekly)',
    seededEmail: 'lena@quartzhalo.live',
  },
  {
    id: 'c012',
    channelName: 'BrassKnucklePixels',
    firstName: 'Diego',
    platform: 'YouTube',
    profileUrl: 'https://youtube.com/@brassknucklepixels',
    acv: 590,
    hoursStreamed: 133,
    followers: 212000,
    lastLive: '2026-08-12',
    kickStatus: 'No Kick presence',
    aboutText:
      '[ABOUT] Fighting game breakdowns, frame data, tournament recaps. [BUSINESS] diego@brasskp.gg',
    seededEmail: 'diego@brasskp.gg',
  },
  {
    id: 'c013',
    channelName: 'SilentAperture',
    firstName: 'Yuki',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/silentaperture',
    acv: 880,
    hoursStreamed: 176,
    followers: 143000,
    lastLive: '2026-08-15',
    kickStatus: 'No Kick presence',
    aboutText:
      '[BIO] photo-mode streams and art commissions. commissions: yuki.art.queue@proton.me [BUSINESS] sponsorship desk — yuki@silentaperture.jp',
    seededEmail: 'yuki@silentaperture.jp',
  },
  {
    id: 'c014',
    channelName: 'RisingArcTV',
    firstName: 'Noor',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/risingarctv',
    acv: 430,
    hoursStreamed: 102,
    followers: 87000,
    lastLive: '2026-08-14',
    kickStatus: 'No Kick presence',
    aboutText:
      '[BIO] rocket league ranked climb, EU evenings [CONTACT] noor@risingtalent.gg',
    seededEmail: 'noor@risingtalent.gg',
  },
  {
    id: 'c015',
    channelName: 'CobaltVespers',
    firstName: 'Elias',
    platform: 'YouTube',
    profileUrl: 'https://youtube.com/@cobaltvespers',
    acv: 1620,
    hoursStreamed: 199,
    followers: 358000,
    lastLive: '2026-08-11',
    kickStatus: 'Active on Kick',
    aboutText: '[ABOUT] Survival craft series. [BUSINESS] elias@cobaltvespers.com',
    seededEmail: 'elias@cobaltvespers.com',
  },
  {
    id: 'c016',
    channelName: 'EmberDriftLive',
    firstName: 'Talia',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/emberdriftlive',
    acv: 1030,
    hoursStreamed: 205,
    followers: 194000,
    lastLive: '2026-08-13',
    kickStatus: 'Active on Kick',
    aboutText: '[BIO] drift sims, car builds [BUSINESS] talia@emberdrift.live',
    seededEmail: 'talia@emberdrift.live',
  },
  {
    id: 'c017',
    channelName: 'GlassCanyonTV',
    firstName: 'Rowan',
    platform: 'YouTube',
    profileUrl: 'https://youtube.com/@glasscanyontv',
    acv: 470,
    hoursStreamed: 118,
    followers: 121000,
    lastLive: '2026-08-16',
    kickStatus: 'Active on Kick',
    aboutText: '[ABOUT] Open-world exploration. [CONTACT] rowan@glasscanyon.tv',
    seededEmail: 'rowan@glasscanyon.tv',
  },
  {
    id: 'c018',
    channelName: 'NocturneRelay',
    firstName: 'Aiko',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/nocturnerelay',
    acv: 355,
    hoursStreamed: 91,
    followers: 66000,
    lastLive: '2026-08-12',
    kickStatus: 'Active on Kick',
    aboutText: '[BIO] late-night rhythm games [BOOKING] aiko@nocturnerelay.fm',
    seededEmail: 'aiko@nocturnerelay.fm',
  },
  {
    id: 'c019',
    channelName: 'LanternPathTV',
    firstName: 'Mira',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/lanternpathtv',
    acv: 210,
    hoursStreamed: 84,
    followers: 44000,
    lastLive: '2026-08-02',
    kickStatus: 'No Kick presence',
    aboutText:
      '[BIO] indie horror first-looks. [FOOTER] keys + sponsorships: mira (at) lanternpath (dot) tv',
    seededEmail: 'mira@lanternpath.tv',
  },
  {
    id: 'c020',
    channelName: 'DriftwoodDeck',
    firstName: 'Hugo',
    platform: 'YouTube',
    profileUrl: 'https://youtube.com/@driftwooddeck',
    acv: 175,
    hoursStreamed: 68,
    followers: 39000,
    lastLive: '2026-07-28',
    kickStatus: 'No Kick presence',
    aboutText: '[ABOUT] Deckbuilder reviews. [CONTACT] hugo@driftwooddeck.com',
    seededEmail: 'hugo@driftwooddeck.com',
  },
  {
    id: 'c021',
    channelName: 'SaltFlatsGaming',
    firstName: 'Zoe',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/saltflatsgaming',
    acv: 260,
    hoursStreamed: 112,
    followers: 58000,
    lastLive: '2026-08-05',
    kickStatus: 'Unverified',
    aboutText: '[BIO] rally + trucking sims [BUSINESS] zoe@saltflats.gg',
    seededEmail: 'zoe@saltflats.gg',
  },
  {
    id: 'c022',
    channelName: 'IronPetalTV',
    firstName: 'Anders',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/ironpetaltv',
    acv: 320,
    hoursStreamed: 79,
    followers: 51000,
    lastLive: '2026-07-30',
    kickStatus: 'No Kick presence',
    aboutText: '[BIO] gardening + JRPGs [CONTACT] anders [at] ironpetal [dot] tv',
    seededEmail: 'anders@ironpetal.tv',
  },
  {
    id: 'c023',
    channelName: 'MothToLampLive',
    firstName: 'Rin',
    platform: 'YouTube',
    profileUrl: 'https://youtube.com/@mothtolamplive',
    acv: 190,
    hoursStreamed: 95,
    followers: 72000,
    lastLive: '2026-08-04',
    kickStatus: 'Active on Kick',
    aboutText: '[ABOUT] Puzzle games, no commentary. [BUSINESS] rin@mothtolamp.jp',
    seededEmail: 'rin@mothtolamp.jp',
  },
  {
    id: 'c024',
    channelName: 'CedarKeepTV',
    firstName: 'Blake',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/cedarkeeptv',
    acv: 155,
    hoursStreamed: 64,
    followers: 21000,
    lastLive: '2026-07-25',
    kickStatus: 'No Kick presence',
    aboutText: '[BIO] survival co-op with friends [CONTACT] blake@cedarkeep.tv',
    seededEmail: 'blake@cedarkeep.tv',
  },
  {
    id: 'c025',
    channelName: 'HalfMoonQueue',
    firstName: 'Freya',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/halfmoonqueue',
    acv: 240,
    hoursStreamed: 103,
    followers: 47000,
    lastLive: '2026-08-06',
    kickStatus: 'No Kick presence',
    aboutText:
      '[BIO] MMO raid nights [MANAGEMENT] all inbound via freya@talentnest.io',
    seededEmail: 'freya@talentnest.io',
  },
  {
    id: 'c026',
    channelName: 'UmberSignal',
    firstName: 'Otto',
    platform: 'YouTube',
    profileUrl: 'https://youtube.com/@umbersignal',
    acv: 205,
    hoursStreamed: 71,
    followers: 33000,
    lastLive: '2026-08-01',
    kickStatus: 'Unverified',
    aboutText: '[ABOUT] Retro hardware restoration. [FOOTER] otto@umbersignal.co',
    seededEmail: 'otto@umbersignal.co',
  },
  {
    id: 'c027',
    channelName: 'PaleHarborTV',
    firstName: 'Nia',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/paleharbortv',
    acv: 290,
    hoursStreamed: 130,
    followers: 64000,
    lastLive: '2026-08-03',
    kickStatus: 'No Kick presence',
    aboutText: '[BIO] fishing games, chill [BOOKING] nia@paleharbor.tv',
    seededEmail: 'nia@paleharbor.tv',
  },
  {
    id: 'c028',
    channelName: 'ThistleAndKey',
    firstName: 'Sam',
    platform: 'YouTube',
    profileUrl: 'https://youtube.com/@thistleandkey',
    acv: 165,
    hoursStreamed: 88,
    followers: 28000,
    lastLive: '2026-07-27',
    kickStatus: 'No Kick presence',
    aboutText:
      '[ABOUT] Cottagecore farming series. [LINKS] no email published — use the YouTube "About" contact button, which is disabled for this channel',
    seededEmail: null,
  },
  {
    id: 'c029',
    channelName: 'GraniteWaltz',
    firstName: 'Leo',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/granitewaltz',
    acv: 275,
    hoursStreamed: 76,
    followers: 42000,
    lastLive: '2026-08-07',
    kickStatus: 'No Kick presence',
    aboutText: '[BIO] climbing sims + chess [CONTACT] leo@granitewaltz.live',
    seededEmail: 'leo@granitewaltz.live',
  },
  {
    id: 'c030',
    channelName: 'VerdantSpoolTV',
    firstName: 'Amara',
    platform: 'YouTube',
    profileUrl: 'https://youtube.com/@verdantspooltv',
    acv: 225,
    hoursStreamed: 121,
    followers: 91000,
    lastLive: '2026-07-31',
    kickStatus: 'No Kick presence',
    aboutText: '[ABOUT] Crafting and cozy co-op. [BUSINESS] amara@verdantspool.tv',
    seededEmail: 'amara@verdantspool.tv',
  },
  {
    id: 'c031',
    channelName: 'TinCanRadioTV',
    firstName: 'Jonas',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/tincanradiotv',
    acv: 85,
    hoursStreamed: 41,
    followers: 12000,
    lastLive: '2026-07-05',
    kickStatus: 'No Kick presence',
    aboutText: '[BIO] talk show + music [CONTACT] jonas@tincanradio.tv',
    seededEmail: 'jonas@tincanradio.tv',
  },
  {
    id: 'c032',
    channelName: 'FernwickPlays',
    firstName: 'Ivy',
    platform: 'YouTube',
    profileUrl: 'https://youtube.com/@fernwickplays',
    acv: 60,
    hoursStreamed: 22,
    followers: 8400,
    lastLive: '2026-06-18',
    kickStatus: 'Unverified',
    aboutText: '[ABOUT] Occasional let’s plays. [CONTACT] ivy@fernwick.gg',
    seededEmail: 'ivy@fernwick.gg',
  },
  {
    id: 'c033',
    channelName: 'BurntSiennaGG',
    firstName: 'Cole',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/burntsiennagg',
    acv: 140,
    hoursStreamed: 58,
    followers: 9600,
    lastLive: '2026-06-29',
    kickStatus: 'No Kick presence',
    aboutText: '[BIO] art streams [CONTACT] cole@burntsienna.gg',
    seededEmail: 'cole@burntsienna.gg',
  },
  {
    id: 'c034',
    channelName: 'LowTideLounge',
    firstName: 'Mei',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/lowtidelounge',
    acv: 310,
    hoursStreamed: 44,
    followers: 15000,
    lastLive: '2026-08-15',
    kickStatus: 'No Kick presence',
    aboutText:
      '[BIO] weekends only, two streams a month [BOOKING] mei@lowtidelounge.com',
    seededEmail: 'mei@lowtidelounge.com',
  },
  {
    id: 'c035',
    channelName: 'OldGrowthTV',
    firstName: 'Ruth',
    platform: 'YouTube',
    profileUrl: 'https://youtube.com/@oldgrowthtv',
    acv: 420,
    hoursStreamed: 165,
    followers: 6200,
    lastLive: '2026-08-14',
    kickStatus: 'No Kick presence',
    aboutText:
      '[ABOUT] Forestry documentaries, tiny sub count, unusually high live audience. [CONTACT] ruth@oldgrowth.tv',
    seededEmail: 'ruth@oldgrowth.tv',
  },
  {
    id: 'c036',
    channelName: 'StaticOrchard',
    firstName: 'Pavel',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/staticorchard',
    acv: 195,
    hoursStreamed: 92,
    followers: 37000,
    lastLive: '2026-06-02',
    kickStatus: 'No Kick presence',
    aboutText: '[BIO] on hiatus until the autumn [CONTACT] pavel@staticorchard.tv',
    seededEmail: 'pavel@staticorchard.tv',
  },
  {
    id: 'c037',
    channelName: 'MidnightAbacus',
    firstName: 'Hana',
    platform: 'YouTube',
    profileUrl: 'https://youtube.com/@midnightabacus',
    acv: 45,
    hoursStreamed: 31,
    followers: 5100,
    lastLive: '2026-07-12',
    kickStatus: 'No Kick presence',
    aboutText: '[ABOUT] Maths puzzle streams. [CONTACT] hana@midnightabacus.co',
    seededEmail: 'hana@midnightabacus.co',
  },
  {
    id: 'c038',
    channelName: 'RustBucketRally',
    firstName: 'Gus',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/rustbucketrally',
    acv: 120,
    hoursStreamed: 49,
    followers: 18000,
    lastLive: '2026-06-25',
    kickStatus: 'Active on Kick',
    aboutText: '[BIO] banger racing [CONTACT] gus@rustbucketrally.uk',
    seededEmail: 'gus@rustbucketrally.uk',
  },
  {
    id: 'c039',
    channelName: 'PorchlightVODs',
    firstName: 'Sena',
    platform: 'YouTube',
    profileUrl: 'https://youtube.com/@porchlightvods',
    acv: 75,
    hoursStreamed: 210,
    followers: 24000,
    lastLive: '2026-05-28',
    kickStatus: 'No Kick presence',
    aboutText:
      '[ABOUT] Enormous airtime, tiny live audience — mostly unlisted VOD dumps. [CONTACT] sena@porchlight.tv',
    seededEmail: 'sena@porchlight.tv',
  },
  {
    id: 'c040',
    channelName: 'HollowdaleTV',
    firstName: 'Ari',
    platform: 'Twitch',
    profileUrl: 'https://twitch.tv/hollowdaletv',
    acv: 165,
    hoursStreamed: 55,
    followers: 13500,
    lastLive: '2026-07-20',
    kickStatus: 'Unverified',
    aboutText: '[BIO] roguelikes, short sessions [BOOKING] ari@hollowdale.tv',
    seededEmail: 'ari@hollowdale.tv',
  },
];

/** Competing agency domains shipped with the demo. The operator can edit these. */
export const blocklistSeed: string[] = [
  'loadedgg.agency',
  'apexcreators.co',
  'talentnest.io',
  'streamforge-rivals.com',
];

/** Creator ids already contacted in a previous scouting round (drives dedupe). */
export const scoutedHistorySeed: string[] = ['c006', 'c012', 'c024'];
